


export const Metadata = {
    title: "Login",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <div>
            {children}
        </div>

    );
}
