
import Navbar from "../navbar";


export const Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (

        <>
            <Navbar />
            <div>
                {children}
            </div>
        </>
    );
}
